### ISSUE TITLE
”MVPリリース”レビュー依頼

### ISSUE THREAD

**Issue by yaJI02** [yaJI02/OshiGoodsGallery#70]
## 各種情報
サービス名：推しグッズギャラリー
サービスURL：https://oshigoodsgallery.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] トップページ
  - [x] 新着記事の表示
  - [x] 利用規約ページの作成
  - [x] プライバシーポリシーの作成
    - [x] お問い合わせフォームの作成
- [x] ユーザーログイン機能
  - [x] user新規登録
  - [x] ログイン・ログアウト機能
- [x] グッズおよびショールーム（post）投稿機能
  - [x] 新規投稿
  - [x] 詳細画面
    - [x] 編集・削除機能（自分の投稿のみ）
  - [x] 一覧画面
- [x] マイページ
  - [x] 自分の投稿一覧を表示
  - [x] プロフィール機能
    - [x] マイベスト投稿登録機能

## READMEレビュー時から変更した機能

- デプロイ先を変更
fly.ioにデプロイ予定でしたが、メモリの関係でrender.comへ変更しました
- お問い合わせ先
SNSアカウントの記載ではなく、お問い合わせフォームを追加

### ログイン
![image](https://github.com/yaJI02/OshiGoodsGallery/assets/133073514/4a0ee075-da6d-438a-94f2-c567c2b9ab68)
### 新規登録
![image](https://github.com/yaJI02/OshiGoodsGallery/assets/133073514/ad129050-ed9e-4278-9914-6cef6bd23110)
### トップページ
![image](https://github.com/yaJI02/OshiGoodsGallery/assets/133073514/42a033ff-1f51-4eaa-a5dc-db67241db2dd)
### 投稿一覧
![image](https://github.com/yaJI02/OshiGoodsGallery/assets/133073514/1e823098-585a-4d47-b7dc-6fdba1f509cc)
### 投稿詳細
![image](https://github.com/yaJI02/OshiGoodsGallery/assets/133073514/9a8edea4-b795-4d11-9a14-be22875f4811)
### マイページ
![image](https://github.com/yaJI02/OshiGoodsGallery/assets/133073514/5466771a-a238-4767-ba7a-153c23d2fd0b)
### プロフィール
![image](https://github.com/yaJI02/OshiGoodsGallery/assets/133073514/b599a388-8c2a-4480-96f0-b361543eb724)
### 問い合わせフォーム
![image](https://github.com/yaJI02/OshiGoodsGallery/assets/133073514/56c56769-39dc-48e3-a881-7b45a4d836fe)

**Comment by Tsuchiya2** [comment]
提出されたURLにアクセスしたのですが、5分程経過してもトップページも表示されない状態です。ご確認と対応をお願いいたします。（デプロイ先の設定を有料化するなど、ご検討ください）

**Comment by yaJI02** [comment]
> 提出されたURLにアクセスしたのですが、5分程経過してもトップページも表示されない状態です。ご確認と対応をお願いいたします。（デプロイ先の設定を有料化するなど、ご検討ください）

本件、一度もサイトにアクセスしたことがないiPhoneや自宅のwindows pcでアクセスしてみたのですが、問題なく開くことができますため、原因が不明です。
エラーメッセージなどが表示されている場合は、画面をお送りいただくことは可能でしょうか？

**Comment by kenchasonakai** [comment]
機能の実装確認できました！
LGTMです！
本リリースに向けて引き続き実装頑張ってください 💪 

URL開けましたが結構時間がかかってしまっていました
Herokuだと30分使われなかったらスリープモードになるみたいなことがあるのでRenderもそのような仕様になっているのかもしれないです
対策としてcronを使って定期的にアクセスするなどがありますので就活までになにか対策を考えておくと良いかもしれません
https://t.gyazo.com/teams/startup-technology/713f53e1b7b7d00df3ab50180d7ddd22.mp4
